service: overwatch-leauge-api-server
provider:
    name: aws
    runtime: nodejs12.x
    region: ap-northeast-2
    stage: dev
    environment:
        END_POINT: https://api.overwatchleague.com

plugins:
    - serverless-webpack
    - serverless-offline

custom:
    webpack:
        webpackConfig: 'webpack.config.js'
        includeModules: false
        packager: 'npm'
        excludeFiles: src/**/*.test.js
    serverless-offline:
        httpPort: 4000

# package:
#     individually: true

# This will switch the plugin to per function packaging
# which makes use of the multi-compiler feature of Webpack.
# That means, that Webpack compiles and optimizes each function individually,
# removing unnecessary imports and reducing code sizes significantly.
# Tree-Shaking only makes sense with this approach.

functions:
    hello:
        handler: dist/service/src/server.hello
        events:
            - http:
                  path: hello
                  method: get
                  cors: true

    getAllLeaugers:
        # handler: src/server.getAllLeaguers
        handler: dist/service/src/server.getAllLeaguers
        events:
            - http:
                  path: leaguers
                  method: get
                  cors: true

    getLeaguerById:
        handler: dist/service/src/server.getLeaguerById
        events:
            - http:
                  path: leaguers/{id}
                  method: get
                  cors: true
